spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://aws-server:3306/local_dating
    #url: jdbc:mysql://localhost:3306/local_dating
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: aws-server
      port: 6379

logging:
  level:
    #org.springframework.web: DEBUG
    #guru.springframework.controllers: DEBUG
    org.springframework.cache: DEBUG
    #org.hibernate: DEBUG
    #org: INFO